Add patch feature to packages and ree

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -220,6 +220,14 @@ RubyWrapper
           rvm_ree_options="${rvm_ree_options} --no-tcmalloc"
         fi
 
+        if [[ ! -z "$rvm_ruby_patch" ]] ; then
+          for patch in $(echo $rvm_ruby_patch | tr ',' ' ') ; do
+            __rvm_run "patch" "patch -p0 -f < $patch" "Applying patch '$patch'..."
+            if [[ $? -gt 0 ]] ; then
+              $rvm_scripts_path/log "error" "Patch $patch did not apply cleanly... back to the patching board :(" ; exit 1
+            fi
+          done
+        fi
 
         __rvm_run "install" "./installer -a $rvm_rubies_path/$rvm_ruby_interpreter-$rvm_ruby_version-$rvm_ruby_patch_level $rvm_ree_options --dont-install-useful-gems $rvm_ruby_configure_flags --no-dev-docs" "Installing $rvm_ruby_string, this may take a while, depending on your cpu(s)..."
           result=$? ; if [[ "$result" -gt 0 ]] ; then
